name: build-and-deploy

on: [push]
      
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t registry.cn-beijing.aliyuncs.com/yoooxin/test:test1 .
      - name: Login In Aliyun
        run: docker login --username=${{secret.TEST_ACR_USERNAME}} --password=${{secret.TEST_ACR_PASSWORD}} registry.cn-beijing.aliyuncs.com
      - name: Push To Aliyun
        run: docker push registry.cn-beijing.aliyuncs.com/yoooxin/test:test1
      
    
