name: build-and-deploy

on:
  push:
    branches:
      - qa
      
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t registry.cn-beijing.aliyuncs.com/yoooxin/test:${{github.ref}}
      - name: Login In Aliyun
        run: docker login --username=yanghuidong@yoooxin --password=yhd19981104 registry.cn-beijing.aliyuncs.com
      - name: Push To Aliyun
        run: docker push registry.cn-beijing.aliyuncs.com/yoooxin/test:${{github.ref}}
      
    
